local Mat = {}

Mat.z1 = '/Game/SandBox/Materials/MatLab/z1.z1'
Mat.z2 = '/Game/SandBox/Materials/MatLab/z2.z2'
Mat.z3 = '/Game/SandBox/Materials/MatLab/z3.z3'
Mat.z4 = '/Game/SandBox/Materials/MatLab/z4.z4'
Mat.t1 = '/Game/SandBox/Materials/MatLab/t1.t1'
Mat.t2 = '/Game/SandBox/Materials/MatLab/t2.t2'
Mat.t3 = '/Game/SandBox/Materials/MatLab/t3.t3'
Mat.t4 = '/Game/SandBox/Materials/MatLab/t4.t4'
Mat.m1 = '/Game/SandBox/Materials/MatLab/m1.m1'
Mat.m2 = '/Game/SandBox/Materials/MatLab/m2.m2'
Mat.l1 = '/Game/SandBox/Materials/MatLab/l1.l1'
Mat.hsFloor = '/Game/SandBox/Materials/MatLab/hsFloor.hsFloor'
Mat.ssFloor = '/Game/SandBox/Materials/MatLab/ssFloor.ssFloor'
Mat.qssnFloor = '/Game/SandBox/Materials/MatLab/qssnFloor.qssnFloor'
Mat.bstwInWall = '/Game/SandBox/Materials/MatLab/bstwInWall.bstwInWall'
Mat.bqInWall = '/Game/SandBox/Materials/MatLab/bqInWall.bqInWall'
Mat.hshztwInWall = '/Game/SandBox/Materials/MatLab/hshztwInWall.hshztwInWall'
Mat.hsgzWall = '/Game/SandBox/Materials/MatLab/hsgzWall.hsgzWall'
Mat.lsFloor = '/Game/SandBox/Materials/MatLab/lsFloor.lsFloor'
Mat.hszkOutWall = '/Game/SandBox/Materials/MatLab/hszkOutWall.hszkOutWall'
Mat.hsInWall = '/Game/SandBox/Materials/MatLab/hsInWall.hsInWall'
Mat.hsOutWall = '/Game/SandBox/Materials/MatLab/hsOutWall.hsOutWall'
Mat.hssztwOutWall = '/Game/SandBox/Materials/MatLab/hssztwOutWall.hssztwOutWall'
Mat.snFloor = '/Game/SandBox/Materials/MatLab/snFloor.snFloor'
Mat.bsgzOutWall = '/Game/SandBox/Materials/MatLab/bsgzOutWall.bsgzOutWall'

return Mat
